spring.application.name=threeh

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.hibernate.ddl-auto=update
spring.devtools.restart.enabled=true

#Toss Payment
payment.toss.test_client_api_key=test_ck_4yKeq5bgrpKLdW2mBbdBVGX0lzW6
payment.toss.test_secrete_api_key=test_sk_k_26DlbXAaV0dqqGlRkRXbVqY50Q9R
payment.toss.success_url=http://localhost:8080/payment/toss/success
payment.toss.fail_url=http://localhost:8080/payment/toss/fail

#기본 프로파일을 local
spring.profiles.active=local