spring.application.name=threeh

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.hibernate.ddl-auto=update
spring.devtools.restart.enabled=true

#기본 프로파일을 local
spring.profiles.active=local