spring.application.name=threeh

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.hibernate.ddl-auto=update
spring.devtools.restart.enabled=true

#Toss Payment
tosspayments.client-key=test_ck_4yKeq5bgrpKLdW2mBbdBVGX0lzW6
tosspayments.secret-key=test_sk_26DlbXAaV0dqqGlRkRXbVqY50Q9R
tosspayments.success-url=http://localhost:8080/payment/toss/success
tosspayemnts.fail-url=http://localhost:8080/payment/toss/fail

#기본 프로파일을 local
spring.profiles.active=local