# 이 파일을 복사해서 application-local.properties 만들고
# 본인 경로로 수정하세요
#단 전자지갑 압축폴더를 압축을 풀고 그 폴더의 경로를 적으세요
spring.datasource.url=jdbc:oracle:thin:@swdb_medium?TNS_ADMIN=C:\Users\human-23\Desktop\파이널프로젝트\Wallet_swDB
spring.datasource.username=admin
spring.datasource.password=@Alibi240319
wallet.path=C:\Users\human-23\Desktop\파이널프로젝트\Wallet_swDB